name: Docker images
on:
  push:
    branches-ignore:
    - master

jobs:
  list-changed-modules:
    runs-on: [ubuntu-latest]
    outputs:
      json: ${{ steps.list.outputs.json }}
      text: ${{ steps.list.outputs.text }}
    steps:
      - name: list
        id: list
        run: |
          echo 'json=["a", "b", "c"]' >> $GITHUB_OUTPUT
  echo:
    runs-on: [ubuntu-latest]
    needs:
      - list-changed-modules
    steps:
      - name: echo
        run: |
          echo 'json=${{ fromJSON(needs.list-changed-modules.outputs.json) }}'
  build-image:
    runs-on: [ubuntu-latest]
    needs:
      - echo
      - list-changed-modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.list-changed-modules.outputs.json) }}
    steps:
      - name: Build docker image
        run: |
          echo ${{ matrix.module }}
