name: Docker images
on:
  push:
    branches-ignore:
    - master

jobs:
  list-changed-modules:
    runs-on: [ubuntu-latest]
    outputs:
      changed-modules: ${{ steps.list-changed-modules.outputs.json }}
    steps:
      - name: list-changed-modules
        run: |
          echo "json=${{ toJSON('[a, b, c]') }}" >> $GITHUB_OUTPUT
  build-changed-modules:
    runs-on: [ubuntu-latest]
    needs:
      - list-changed-modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.list-changed-modules.outputs.changed-modules) }}
    steps:
      - name: build-changed-modules
        run: |
          echo ${{ matrix.module }}
